# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=1.21.1

# Fabric
loader_version=0.15.11
fabric_api_version=0.102.0+1.21.1

# Loom
loom_version=1.6.12

# Mod
mod_version=1.0.0
maven_group=miprimermod
archives_base_name=prueba-mod
